services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '80:80'
    depends_on:
      - db
